Neos:
  Flow:
    http:
      middlewares:
        'Flownative.OpenIdConnect.Client:setJwtCookie':
          'position': 'after session'
          middleware: 'Flownative\OpenIdConnect\Client\Http\SetJwtCookieMiddleware'

Flownative:
  OpenIdConnect:
    Client:
      middleware:
        authenticationProviderName: 'Flownative.OpenIdConnect.Client:OidcProvider'
        cookie:
          name: 'flownative_oidc_jwt'
          secure: true
          sameSite: 'strict'
          httpOnly: false
